language: node_js # 设置语言
node_js: stable # 设置语言版本

cache:
  directories:
    - node_modules # 缓存依赖

before_install:
  - npm install -g hexo-cli

# S: Build Lifecycle
install:
  - npm install


before_script:
  - git config user.name "Lampkins"
  - git config user.email "1726538752@qq.com"
  # 将_config.yml中的'git@github.com:'替换为'https://${GH_TOKEN}@github.com/''
  - sed -i "s~git@github.com:~https://${GH_TOKEN}@github.com/~" _config.yml
  

script:
  - hexo clean # 清空原public
  - hexo generate --force # 生成public
  - hexo deploy > /dev/null # 部署

# after_script: 
  # - git add .
  # - git commit -am "Travis CI Build:$date '+%Y-%m-%d %H:%M:%S' -d '+8 hour"
  # - git push origin master:master
# E: Build LifeCycle

branches:
  only:
    - hexo-source
env:
 global:
   - GH_REF: github.com/Lampkins/Lampkins.github.io.git